[pytest]
DJANGO_SETTINGS_MODULE=storefront.settings

filterwarnings =
    ignore:.*pkg_resources.*:UserWarning
    ignore:.*cgi.*:DeprecationWarning
    ignore:.*utcfromtimestamp.*:DeprecationWarning
